language: cpp
compiler:
  - gcc
  - clang

os:
  - linux
  - osx

dist: trusty
sudo: required

env:
  matrix:
    # The CMake setup does not afford testing in Release mode yet
    # - BUILDTYPE=Release
    - BUILDTYPE=Debug

matrix:
  exclude:
    # gcc is just an alias for clang on OS X, so remove the rsp. build for now
    - os: osx
      compiler: gcc

# Note: For clang builds, a gcc-6 environment is set up as well so that a
# C++14-compliant libstdc++ can be used.
before_script:
  - if [ `uname` = "Linux" ]; then
      wget -nv -O - http://llvm.org/apt/llvm-snapshot.gpg.key | sudo apt-key add - ;
      sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test ;
      sudo add-apt-repository -y "deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-4.0 main" ;
      sudo apt-get update ;
    fi
  - if [ "$CXX" = "g++" ]; then
      sudo apt-get install -y --force-yes g++-6 ;
      export CC=gcc-6 ;
      export CXX=g++-6 ;
    fi
  - if [ "$CXX" = "clang++" ]; then
      sudo apt-get install -y --force-yes g++-6 ;
      sudo apt-get install -y --force-yes clang-4.0 ;
      export CC=clang-4.0 ;
      export CXX=clang++-4.0 ;
    fi

script:
  - mkdir -p ../build
  - cd ../build
  - cmake -DCMAKE_BUILD_TYPE=${BUILDTYPE} ../state_ptr
  - cmake --build . -- -j2
  - ctest -V
